name: EC2-Deployment

on:
  push:
    branches: [ main ] # Main branch la code push panna ithu run agum

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Clone or Pull the Repo
            if [ -d "~/my-app" ]; then
              cd ~/my-app && git pull origin main
            else
              git clone https://github.com/poorna942-glitch/aws-ecs-cicd-project.git ~/my-app
              cd ~/my-app
            fi

            # Build and Restart Container
            sudo docker build -t aitech-cicd .
            sudo docker stop aitech-web || true
            sudo docker rm aitech-web || true
            sudo docker run -d -p 80:80 --name aitech-web aitech-cicd
